CREATE TABLE IF NOT EXISTS CLIENTES (
      ID VARCHAR(36) PRIMARY KEY,
      LIMITE BIGINT,
      SALDO_INICIAL BIGINT,
      SALDO BIGINT
);

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
      ID VARCHAR(36) PRIMARY KEY
      VALOR BIGINT,
      TIPO CHAR,
      I_CLIENTES VARCHAR(36),
      DESCRICAO VARCHAR(100),
      FOREIGN KEY (I_CLIENTES) REFERENCES CLIENTES(ID)
);
