CREATE SEQUENCE CLIENTES_ID_SEQ;

CREATE TABLE IF NOT EXISTS CLIENTES (
      ID INT DEFAULT NEXTVAL('CLIENTES_ID_SEQ')PRIMARY KEY,
      LIMITE BIGINT,
      SALDO_INICIAL BIGINT,
      SALDO BIGINT
);

CREATE SEQUENCE TRANSACAO_ID_SEQ;

CREATE TABLE IF NOT EXISTS TRANSACTIONS (
      ID INT DEFAULT NEXTVAL('TRANSACAO_ID_SEQ') PRIMARY KEY
      VALOR BIGINT,
      TIPO CHAR,
      I_CLIENTES VARCHAR(36),
      DESCRICAO VARCHAR(100),
      FOREIGN KEY (I_CLIENTES) REFERENCES CLIENTES(ID)
);

INSERT INTO CLIENTES (1, 100000, 0);
INSERT INTO CLIENTES (2, 80000, 0);
INSERT INTO CLIENTES (3, 1000000, 0);
INSERT INTO CLIENTES (4, 10000000, 0);
INSERT INTO CLIENTES (5, 500000, 0);
